.org 0x0
 	.global _start
_start:
    lui x1, 0x1
    nop
    nop
    nop
    nop
    lui x2, 0x2
    nop
    nop
    nop
    nop
    add x3,x1,x2
    nop
    nop
    nop
    nop
    addi x3,x2,0x3
    nop
    nop
    nop
    nop
    sub x4,x2,x3
    nop
    nop
    nop
    nop
    lui x1, 0x1
    nop
    nop
    nop
    nop
    lui x2, 0x2
    nop
    nop
    nop
    nop
    srli x2,x2,0xc
    nop
    nop
    nop
    nop
    sll x3,x1,x2
    nop
    nop
    nop
    nop
    slli x3,x1,0x2
    nop
    nop
    nop
    nop
    lui x1,0x4
    nop
    nop
    nop
    nop
    srl x3,x1,x2
    nop
    nop
    nop
    nop
    srli x3,x1,0x2
    nop
    nop
    nop
    nop
    lui x1,2
    nop
    nop
    nop
    nop
    sub x1,x0,x1
    nop
    nop
    nop
    nop
    lui x2,0x1
    nop
    nop
    nop
    nop
    srli x2,x2,0xc
    nop
    nop
    nop
    nop
    sra x3,x1,x2
    nop
    nop
    nop
    nop
    srai x3,x1,0x1
    nop
    nop
    nop
    nop
    slt x3,x1,x2
    nop
    nop
    nop
    nop
    slti x3,x1,0x1
    nop
    nop
    nop
    nop
    sltu x3,x1,x2
    nop
    nop
    nop
    nop
    sltiu x3,x1,0x1
    nop
    nop
    nop
    nop
    xor x3,x1,x2
    nop
    nop
    nop
    nop
    xori x3,x1,0x1
    nop
    nop
    nop
    nop
    or x3,x1,x2
    nop
    nop
    nop
    nop
    ori x3,x1,0x1
    nop
    nop
    nop
    nop
    and x3,x1,x2
    nop
    nop
    nop
    nop
    andi x3,x1,0x1
    nop
    nop
    nop
    nop
    auipc x3,0x1
    nop
    nop
    nop
    nop
    
